
[build]
  publish = "frontend/.next"
  command = "npm install && cd frontend && npm install && npm run build"

[functions]
  directory = "backend/src/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
